### ISSUE TITLE
KeyboardInterrupt used for flow control

### ISSUE THREAD

**Issue by cool-RR** [P403n1x87/austin-tui#10]
I saw that you use `KeyboardInterrupt` in a bunch of places. Raising it and catching it. I've never seen it done that way in a long career of Python programming. Admittedly I haven't touched many async-await code, so maybe it's prevalent there?

In any case, are you sure it's a natural way to do flow control? Why does a quit signal need to be a `KeyboardInterrupt`, can't you just make an exception class for that?

**Comment by P403n1x87** [comment]
I don't think this is standard practice. The rationale behind it is that `KeyboardInterrupt` is, at least in this case, equivalent to pressing `Q` to quit the TUI. Given that the handling is then the same, I decided to use `KeyboardInterrupt` to signal a termiantion request from the user. It's certanly not the cleanest approach, as it could lead to all sorts of bad things as the complexity grows, and perhaps the need to distinguish between `Ctrl+C` from `Q` actually arises. This might get fixed in the future by introducing a dedicated exception, as you suggest.
